export const ValidationMessages = {
  email: 'Incorrect email',
  password: 'Password must contain at least one capital letter, lower case letter and number',
  passwordDontMatch: 'Passwords do not match',
  passwordsAreTheSame: 'Your current password and new password are the same',
  firstName: 'First name must be from 2 to 30 characters long',
  lastName: 'Last name must be from 2 to 30 characters long',
  phoneNumber:  'Must be a numeric value from 12 to 16 integers long',
  flat: 'Must be a positive number',
  productName: "The name must be of size between 2 and 30, start with 2 characters, contain only characters, spaces and numbers",
  price: "The price must be greater than 0",
  quantity: "Must be equal or greater than 0",
  file: "The file extension should be only '.png', should be less than 1Mb and 512x512 px",
  offeredPrice: "The offered price must be greater than 0",
  required: "The field can not be empty",
  time: "Еhe field must be filled in the format: 'HH:MM:SS'",
  expansion: "Picture expansion should only be 'png'",
  weight: "Picture resolution can only be 512 px by 512 px",
  resolution: "The file must not weigh more than 1 MB"
}
