export enum UserRole {
  ROLE_NO_AUTH_CUSTOMER = "ROLE_NO_AUTH_CUSTOMER",
  ROLE_CUSTOMER = "ROLE_CUSTOMER",
  ROLE_COURIER = "ROLE_COURIER",
  ROLE_ADMIN = "ROLE_ADMIN",
  ROLE_PRODUCT_MGR = "ROLE_PRODUCT_MGR"
}
