export enum Route {
  LOGIN = "login",
  REGISTER ="register",
  CONFIRM_TOKEN = "confirm-token/:token",
  NEW_PASSWORD = "new-password/:token",
  FIRST_PASSWORD = "first-password/:token",
  PASSWORD = "reset-password",
  CATALOG = "catalog",
  PRODUCT = "product",
  COMPARE = "compare",
  CART = "cart",
  CHECK_OUT = "check-out",
  AUCTIONS = "auth-store/auction-list",
  AUCTION_PAGE = "auth-store/auction",
  PROFILE = "me",
  STAFF_LIST = "admin/staff",
  STAFF_PROFILE = "admin/staffer/:id",
  STAFF_CREATE = "admin/create-staff",
  ORDER_HISTORY = "customer/order-history",
  ORDER_PAGE = "customer/order",
  CREATE_PRODUCT = "mgr/create-product",
  CREATE_AUCTION = "mgr/create-auction",
  STOCK = "mgr/stock",
  DELIVERIES = "courier/deliveries"
}
